 CREATE DATABASE RETAILS;
USE RETAILS;
use schema PUBLIC;

CREATE OR REPLACE TABLE demographic_RAW
(AGE_DESC	CHAR(20),
MARITAL_STATUS_CODE	CHAR(5),
INCOME_DESC	VARCHAR(40),
HOMEOWNER_DESC	VARCHAR(40),
HH_COMP_DESC	VARCHAR(50),
HOUSEHOLD_SIZE_DESC	VARCHAR(50),
KID_CATEGORY_DESC	VARCHAR(40),
household_key INT PRIMARY KEY
);

CREATE OR REPLACE TABLE CAMPAIGN_DESC_RAW
(DESCRIPTION CHAR(10),	
CAMPAIGN	INT ,
START_DAY	INT,
END_DAY INT,
PRIMARY KEY (DESCRIPTION),
UNIQUE (CAMPAIGN));




CREATE OR REPLACE TABLE CAMPAIGN_RAW
(DESCRIPTION	CHAR(10) ,
household_key	INT,
CAMPAIGN INT,
FOREIGN KEY (DESCRIPTION) references CAMPAIGN_DESC_RAW(DESCRIPTION) ,
FOREIGN KEY (CAMPAIGN) references CAMPAIGN_DESC_RAW(CAMPAIGN),
FOREIGN KEY (household_key) references demographic_RAW(household_key)
);

CREATE OR REPLACE TABLE PRODUCT_RAW
(PRODUCT_ID	INT PRIMARY KEY,
MANUFACTURER 	INT,
DEPARTMENT	VARCHAR(50),
BRAND	VARCHAR(30),
COMMODITY_DESC	VARCHAR(65),
SUB_COMMODITY_DESC VARCHAR(65)	,
CURR_SIZE_OF_PRODUCT VARCHAR(15)
);


CREATE OR REPLACE TABLE COUPON_RAW
(COUPON_UPC	INT,
PRODUCT_ID	INT,
CAMPAIGN INT,
FOREIGN KEY (PRODUCT_ID) references PRODUCT_RAW(PRODUCT_ID),
FOREIGN KEY (CAMPAIGN) references CAMPAIGN_DESC_RAW(CAMPAIGN)
);


CREATE OR REPLACE TABLE COUPON_REDEMPT_RAW
(household_key	INT,
DAY	INT,
COUPON_UPC	INT,
CAMPAIGN INT,
FOREIGN KEY (household_key) references demographic_RAW(household_key),
FOREIGN KEY (CAMPAIGN) references CAMPAIGN_DESC_RAW(CAMPAIGN)
);

CREATE OR REPLACE TABLE TRANSACTION_RAW 
(household_key	INT,
BASKET_ID	INT,
DAY	INT,
PRODUCT_ID	INT,
QUANTITY	INT,
SALES_VALUE	FLOAT,
STORE_ID	INT,
RETAIL_DISC	FLOAT,
TRANS_TIME	INT,
WEEK_NO	INT,
COUPON_DISC	INT,
COUPON_MATCH_DISC INT,
FOREIGN KEY (PRODUCT_ID) references PRODUCT_RAW(PRODUCT_ID),
FOREIGN KEY (household_key) references demographic_RAW(household_key)
);



----------------------------------------------------AWS (S3) INTEGRATION------------------------------------------------------------------------

CREATE OR REPLACE STORAGE integration s3_int
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN ='arn:aws:iam::767179190646:role/Retail_role' 
STORAGE_ALLOWED_LOCATIONS =('s3://retailraw-1/');


DESC integration s3_int;
Create or replace file format CSV
type='CSV',
field_delimiter=',',
skip_header=1;


CREATE OR REPLACE STAGE RETAIL
URL ='s3://retailraw-1'
file_format = CSV
storage_integration = s3_int;

LIST @RETAIL;

SHOW STAGES;
--CREATE SNOWPIPE THAT RECOGNISES CSV THAT ARE INGESTED FROM EXTERNAL STAGE AND COPIES THE DATA INTO EXISTING TABLE

--The AUTO_INGEST=true parameter specifies to read 
--- event notifications sent from an S3 bucket to an SQS queue when new data is ready to load.


copy into "RETAILS"."PUBLIC"."DEMOGRAPHIC_RAW"
from @RETAIL/DEMOGRAPHIC/hh_demographic.csv
FILE_FORMAT = ( FORMAT_NAME = 'CSV');  

copy into "RETAILS"."PUBLIC"."CAMPAIGN_DESC_RAW"
from @RETAIL/CAMPAIGN_DESC/campaign_desc.csv
FILE_FORMAT = ( FORMAT_NAME = 'CSV'); 

copy into "RETAILS"."PUBLIC"."CAMPAIGN_RAW"
from @RETAIL/CAMPAIGN/campaign_table.csv
FILE_FORMAT = ( FORMAT_NAME = 'CSV');  

copy into "RETAILS"."PUBLIC"."PRODUCT_RAW"
from @RETAIL/PRODUCT/product.csv
FILE_FORMAT = ( FORMAT_NAME = 'CSV');  

copy into "RETAILS"."PUBLIC"."COUPON_RAW"
from @RETAIL/COUPON/coupon.csv
FILE_FORMAT = ( FORMAT_NAME = 'CSV'); 

copy into "RETAILS"."PUBLIC"."COUPON_REDEMPT_RAW"
from @RETAIL/COUPON_REDEMPT/coupon_redempt.csv
FILE_FORMAT = ( FORMAT_NAME = 'CSV');  

copy into "RETAILS"."PUBLIC"."TRANSACTION_RAW"
from @RETAIL/TRANSACTION/trnx177_353.csv
FILE_FORMAT = ( FORMAT_NAME = 'CSV');  


SELECT COUNT(*) FROM demographic_RAW;
SELECT COUNT(*) FROM CAMPAIGN_DESC_RAW;
SELECT COUNT(*) FROM CAMPAIGN_RAW;
SELECT COUNT(*) FROM PRODUCT_RAW;
SELECT COUNT(*) FROM COUPON_RAW;
SELECT COUNT(*) FROM COUPON_REDEMPT_RAW;
SELECT COUNT(*) FROM TRANSACTION_RAW;


---------DATA Preview-------------------------------------------

SELECT * FROM demographic_RAW;
SELECT * FROM CAMPAIGN_DESC_RAW;
SELECT * FROM CAMPAIGN_RAW;
SELECT * FROM PRODUCT_RAW;
SELECT * FROM COUPON_RAW;
SELECT * FROM COUPON_REDEMPT_RAW;
SELECT * FROM TRANSACTION_RAW;
